function recomputeEstimateFLEDynamicStats(casename)

outfilename = sprintf('%s.txt', casename);
outfilename2 = sprintf('%sLaTeX.txt',casename);
fid = fopen(outfilename, 'wt');
fid2 = fopen(outfilename2, 'wt');
fprintf(fid, 'Casename: %s\n\n', casename);
fprintf(fid2, 'Casename: %s\n\n', casename);

load(casename);
nMrks = length(stats);

for i = 1:nMrks
    % note we ignore the first set of frames where the covariance matrix is
    % being updated.
    
    winsize = stats{i}.winsize;
    %RMS.
    stats{i}.RMS.error = stats{i}.RMS.estimated((2*winsize+1):end)...
        - stats{i}.RMS.true((2*winsize+1):end);
    stats{i}.RMS.mean = mean(stats{i}.RMS.error);
    stats{i}.RMS.std = std(stats{i}.RMS.error);
    stats{i}.RMS.rms = sqrt(mean((stats{i}.RMS.error).^2));
    stats{i}.RMS.perc95 = [getPercentile(stats{i}.RMS.error,0.025), ...
        getPercentile(stats{i}.RMS.error,0.975)];
    fprintf(fid,'Stats Mrk #%2d\n\tMean\t\tStDev\t\tRMS\t\t95%%Low\t\t95%%Up\nRMS\t% f\t% f\t% f\t% f\t% f\n', i,...
        stats{i}.RMS.mean, stats{i}.RMS.std, stats{i}.RMS.rms, ...
        stats{i}.RMS.perc95(1), stats{i}.RMS.perc95(2));
    fprintf(fid2,'Stats Mrk #%2d\n\tMean\t\tRMS\t\t95%%Low\t\t95%%Up\nRMS\t% 4.4f & % 4.4f & % 4.4f & % 4.4f\n', i,...
        stats{i}.RMS.mean, stats{i}.RMS.rms, ...
        stats{i}.RMS.perc95(1), stats{i}.RMS.perc95(2));
    %sigma_11
    stats{i}.sigma11.error = stats{i}.sigma11.estimated(1,(2*winsize+1):end)...
        - stats{i}.sigma11.true(1,(2*winsize+1):end);
    stats{i}.sigma11.mean = mean(stats{i}.sigma11.error);
    stats{i}.sigma11.std = std(stats{i}.sigma11.error);
    stats{i}.sigma11.rms = sqrt(mean((stats{i}.sigma11.error).^2));
    stats{i}.sigma11.perc95 = [getPercentile(stats{i}.sigma11.error,0.025),...
        getPercentile(stats{i}.sigma11.error,0.975)];
    fprintf(fid,'S11\t% f\t% f\t% f\t% f\t% f\n',...
        stats{i}.sigma11.mean, stats{i}.sigma11.std, stats{i}.sigma11.rms, ...
        stats{i}.sigma11.perc95(1), stats{i}.sigma11.perc95(2));
    fprintf(fid2,'S11\t% 4.4f & % 4.4f & % 4.4f & % 4.4f\n',...
        stats{i}.sigma11.mean, stats{i}.sigma11.rms, ...
        stats{i}.sigma11.perc95(1), stats{i}.sigma11.perc95(2));
    %sigma_12
    stats{i}.sigma12.error = stats{i}.sigma12.estimated(1,(2*winsize+1):end)...
        - stats{i}.sigma12.true(1,(2*winsize+1):end);
    stats{i}.sigma12.mean = mean(stats{i}.sigma12.error);
    stats{i}.sigma12.std = std(stats{i}.sigma12.error);
    stats{i}.sigma12.rms = sqrt(mean((stats{i}.sigma12.error).^2));
    stats{i}.sigma12.perc95 = [getPercentile(stats{i}.sigma12.error,0.025),...
        getPercentile(stats{i}.sigma12.error,0.975)];
    fprintf(fid,'S12\t% f\t% f\t% f\t% f\t% f\n',...
        stats{i}.sigma12.mean, stats{i}.sigma12.std, stats{i}.sigma12.rms, ...
        stats{i}.sigma12.perc95(1), stats{i}.sigma12.perc95(2));
    fprintf(fid2,'S12\t% 4.4f & % 4.4f & % 4.4f & % 4.4f\n',...
        stats{i}.sigma12.mean, stats{i}.sigma12.rms, ...
        stats{i}.sigma12.perc95(1), stats{i}.sigma12.perc95(2));
    %sigma_13
    stats{i}.sigma13.error = stats{i}.sigma13.estimated(1,(2*winsize+1):end)...
        - stats{i}.sigma13.true(1,(2*winsize+1):end);
    stats{i}.sigma13.mean = mean(stats{i}.sigma13.error);
    stats{i}.sigma13.std = std(stats{i}.sigma13.error);
    stats{i}.sigma13.rms = sqrt(mean((stats{i}.sigma13.error).^2));
    stats{i}.sigma13.perc95 = [getPercentile(stats{i}.sigma13.error,0.025),...
        getPercentile(stats{i}.sigma13.error,0.975)];
    fprintf(fid,'S13\t% f\t% f\t% f\t% f\t% f\n',...
        stats{i}.sigma13.mean, stats{i}.sigma13.std, stats{i}.sigma13.rms, ...
        stats{i}.sigma13.perc95(1), stats{i}.sigma13.perc95(2));
    fprintf(fid2,'S13\t% 4.4f & % 4.4f & % 4.4f & % 4.4f\n',...
        stats{i}.sigma13.mean, stats{i}.sigma13.rms, ...
        stats{i}.sigma13.perc95(1), stats{i}.sigma13.perc95(2));
    %sigma_22
    stats{i}.sigma22.error = stats{i}.sigma22.estimated(1,(2*winsize+1):end)...
        - stats{i}.sigma22.true(1,(2*winsize+1):end);
    stats{i}.sigma22.mean = mean(stats{i}.sigma22.error);
    stats{i}.sigma22.std = std(stats{i}.sigma22.error);
    stats{i}.sigma22.rms = sqrt(mean((stats{i}.sigma22.error).^2));
    stats{i}.sigma22.perc95 = [getPercentile(stats{i}.sigma22.error,0.025),...
        getPercentile(stats{i}.sigma22.error,0.975)];
    fprintf(fid,'S22\t% f\t% f\t% f\t% f\t% f\n',...
        stats{i}.sigma22.mean, stats{i}.sigma22.std, stats{i}.sigma22.rms, ...
        stats{i}.sigma22.perc95(1), stats{i}.sigma22.perc95(2));
    fprintf(fid2,'S22\t% 4.4f & % 4.4f & % 4.4f & % 4.4f\n',...
        stats{i}.sigma22.mean, stats{i}.sigma22.rms, ...
        stats{i}.sigma22.perc95(1), stats{i}.sigma22.perc95(2));
    %sigma_23
    stats{i}.sigma23.error = stats{i}.sigma23.estimated(1,(2*winsize+1):end)...
        - stats{i}.sigma23.true(1,(2*winsize+1):end);
    stats{i}.sigma23.mean = mean(stats{i}.sigma23.error);
    stats{i}.sigma23.std = std(stats{i}.sigma23.error);
    stats{i}.sigma23.rms = sqrt(mean((stats{i}.sigma23.error).^2));
    stats{i}.sigma23.perc95 = [getPercentile(stats{i}.sigma23.error,0.025),...
        getPercentile(stats{i}.sigma23.error,0.975)];
    fprintf(fid,'S23\t% f\t% f\t% f\t% f\t% f\n',...
        stats{i}.sigma23.mean, stats{i}.sigma23.std, stats{i}.sigma23.rms, ...
        stats{i}.sigma23.perc95(1), stats{i}.sigma23.perc95(2));
    fprintf(fid2,'S23\t% 4.4f & % 4.4f & % 4.4f & % 4.4f\n',...
        stats{i}.sigma23.mean, stats{i}.sigma23.rms, ...
        stats{i}.sigma23.perc95(1), stats{i}.sigma23.perc95(2));
    %sigma_33
    stats{i}.sigma33.error = stats{i}.sigma33.estimated(1,(2*winsize+1):end)...
        - stats{i}.sigma33.true(1,(2*winsize+1):end);
    stats{i}.sigma33.mean = mean(stats{i}.sigma33.error);
    stats{i}.sigma33.std = std(stats{i}.sigma33.error);
    stats{i}.sigma33.rms = sqrt(mean((stats{i}.sigma33.error).^2));
    stats{i}.sigma33.perc95 = [getPercentile(stats{i}.sigma33.error,0.025),...
        getPercentile(stats{i}.sigma33.error,0.975)];
    fprintf(fid,'S33\t% f\t% f\t% f\t% f\t% f\n',...
        stats{i}.sigma33.mean, stats{i}.sigma33.std, stats{i}.sigma33.rms, ...
        stats{i}.sigma33.perc95(1), stats{i}.sigma33.perc95(2));
    fprintf(fid2,'S33\t% 4.4f & % 4.4f & % 4.4f & % 4.4f\n',...
        stats{i}.sigma33.mean, stats{i}.sigma33.rms, ...
        stats{i}.sigma33.perc95(1), stats{i}.sigma33.perc95(2));
end

fclose('all');